#!/usr/bin/env bash
# Bash script that will display information about subdomains.

if [[ -z "$2" ]]; then
    for i in "www" "lb-01" "web-01" "web-02"; do
        A_RECORD=$(dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
        GET_IP=$(dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        echo "The subdomain $i is a $A_RECORD record and points to $GET_IP"
    done
else
    A_RECORD=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    GET_IP=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $A_RECORD record and points to $GET_IP"
fi
