#!/usr/bin/env bash
# Bash script to install and configurate nginx on port 80 
sudo apt update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "<head>
    <title>New Page</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>" > /var/www/html/index.html
