#!/usr/bin/env bash
# Bash script to install and configurate nginx on port 80 
sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx star
