#!/usr/bin/env bash
# Bash script to install and configurate nginx on port 80 
sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\nerror_page 404 /error404.html;\nlocation =  /error404.html {\n\troot /var/www/html/;\n\tinternal;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo service nginx start
