#!/usr/bin/env bash
# Bash script to install and configurate HAproxy
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt update
apt-get install -y haproxy
SERVERS="frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 34.138.186.79 check\n\tserver web-02 34.236.145.29 check\n"
echo "$SERVERS" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
