#!/usr/bin/env bash
# Bash script to install and configurate HAproxy
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt update
apt-get install -y haproxy
SERVERS="
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.138.186.79:80 check
    server web-02 34.236.145.29:80 check
"
echo "$SERVERS" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
