#!/usr/bin/env bash
# This script is displaying To infinity and beyond indefinitely
_term() { 
  echo "I am invincible!!!"   
}
trap _term SIGTERM
while : 
do
    echo "To infinity and beyond"
    sleep 2
done
