#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1
n=21
china=4
japan=9
italy=17
while (( i < n )); do
    echo "$i"
    case $i in
        $china)
            echo "bad luck from China"
            ;;
        $japan)
            echo "bad luck from Japan"
            ;;
        $italy)
            echo "bad luck from Italy"
            ;;            
    esac
    ((i++))
done