#!/usr/bin/env bash
# Bash script to run Nginx process as user Nginx in port 8080
pkill apache2
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo chmod 666 /etc/nginx/nginx.conf
sudo -u nginx service nginx start